[package]
name = "rust-multithreaded-server"
version = "0.1.0"
authors = ["Lingkai Shen <slk49@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
